version: '3'

services:
  database-servicio:
    image: "postgres" # use latest official postgres version
    env_file:
      - ./database_postgresql/database.env # se configura postgres
    volumes:
      - ./database_postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql # persistir la informacion
      - database-data:/var/lib/postgresql/data/
    ports:
      - "532:5432"
    networks:
      - app-tier
    container_name: postgresqlgmo_service

  faker-servicio:
    restart: always
    build: ./faker
    volumes:
      - ./faker:/usr/src/app
    ports:
      - 5000:3000
    networks:
      - app-tier
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - database-servicio
    container_name: servicio_datos_falsos_gmo

  api-servicio:
    restart: always
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5001:81
    depends_on:
      - faker-servicio
    networks:
      - app-tier
    environment:
      - PYTHONUNBUFFERED=1
    container_name: servicio_api_gmo

  web-servicio:
    restart: always
    build: ./web
    ports:
      - 8003:82
    networks:
      - app-tier
    environment:
      - PYTHONUNBUFFERED=1
    container_name: servicio_web_app_gmo

networks:
  app-tier:
    driver: bridge
volumes:
  database-data:


